apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devfest
data:
  version: "fdfffsa"
  pippo: "ffsd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devfest
data:
  version: "fcffsda"
  pippo: "ffsd"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devfest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:1.27
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devfest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nginx:1.27
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: devfest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: nginx:1.27

---
apiVersion: restart.example.com/v1alpha1
kind: RestartPlan
metadata:
  name: restartplan-sample
  namespace: devfest
  labels:
    app.kubernetes.io/name: restartplan
    app.kubernetes.io/managed-by: kustomize
spec:
  configMap: app-config
  deployments:
    - frontend
    - backend
    - worker
  paused: false

---

apiVersion: restart.example.com/v1alpha1
kind: RestartPlan
metadata:
  name: restartplan-sample-1
  namespace: devfest
  labels:
    app.kubernetes.io/name: restartplan
    app.kubernetes.io/managed-by: kustomize
spec:
  configMap: backend-config
  deployments:
    - backend
    - worker
  paused: false